"""Generate runnable Python source from a RAD design dict."""

from __future__ import annotations

import re
from typing import Any

from .schema import WIDGET_REGISTRY


def _to_class_name(title: str) -> str:
    """Convert a title string to a PascalCase class name."""
    words = re.sub(r"[^a-zA-Z0-9]+", " ", title).split()
    if not words:
        return "MyApp"
    return "".join(w.capitalize() for w in words) + "App"


def _repr_value(value: Any) -> str:
    """Produce a Python repr suitable for code generation."""
    if isinstance(value, str):
        return repr(value)
    if isinstance(value, bool):
        return "True" if value else "False"
    if isinstance(value, list):
        items = ", ".join(repr(v) for v in value)
        return f"[{items}]"
    return str(value)


def generate_python(data: dict) -> str:
    """Generate a complete runnable Python file from a RAD design dict."""
    app_cfg = data.get("app", {})
    theme = app_cfg.get("theme", "light")
    title = app_cfg.get("title", "My App")
    class_name = _to_class_name(title)

    # Collect needed imports
    imports: set[str] = {"App", "Window"}
    all_handlers: set[str] = set()
    has_radio_group = False
    has_menus = bool(data.get("menus"))

    for window_data in data.get("windows", []):
        for w in window_data.get("widgets", []):
            imports.add(w["type"])
            for handler_name in w.get("events", {}).values():
                if handler_name:
                    all_handlers.add(handler_name)
            if w["type"] == "RadioButton" and w.get("props", {}).get("group"):
                has_radio_group = True

    if has_radio_group:
        imports.add("RadioGroup")

    if has_menus:
        imports.update({"MenuBar", "Menu", "MenuItem"})
        for menu in data["menus"]:
            for item in menu.get("items", []):
                handler = item.get("handler", "")
                if handler:
                    all_handlers.add(handler)

    lines: list[str] = []
    lines.append("#!/usr/bin/env python3")
    lines.append(f'"""Generated by runtui RAD Designer — {title}."""')
    lines.append("")
    lines.append("import sys")
    lines.append("import os")
    lines.append("")
    lines.append("# Add parent dir to path")
    lines.append('sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))')
    lines.append("")
    lines.append("from runtui import (")
    lines.append("    " + ", ".join(sorted(imports)) + ",")
    lines.append(")")
    lines.append("from runtui.widgets.container import Container")
    lines.append("from runtui.layout.absolute import AbsoluteLayout")
    lines.append("")
    lines.append("")
    lines.append(f"class {class_name}(App):")
    lines.append(f'    """Application: {title}."""')
    lines.append("")
    lines.append("    def __init__(self) -> None:")
    lines.append(f'        super().__init__(theme="{theme}")')
    lines.append("")
    lines.append("    def on_ready(self) -> None:")

    for window_data in data.get("windows", []):
        win_id = window_data.get("id", "main_window")
        win_title = window_data.get("title", "Window")
        wx = window_data.get("x", 5)
        wy = window_data.get("y", 2)
        ww = window_data.get("width", 40)
        wh = window_data.get("height", 20)

        lines.append(f"        self.{win_id} = Window(")
        lines.append(f'            title="{win_title}",')
        lines.append(f"            x={wx}, y={wy}, width={ww}, height={wh},")
        lines.append("        )")
        lines.append("")
        lines.append("        content = Container()")
        lines.append("        content._layout_manager = AbsoluteLayout()")
        lines.append("")

        # Emit radio groups
        groups_emitted: set[str] = set()
        for w in window_data.get("widgets", []):
            if w["type"] == "RadioButton":
                g = w.get("props", {}).get("group", "")
                if g and g not in groups_emitted:
                    lines.append(f"        {g} = RadioGroup()")
                    groups_emitted.add(g)
        if groups_emitted:
            lines.append("")

        # Emit widgets
        for w in window_data.get("widgets", []):
            wtype = w["type"]
            wid = w.get("id", "widget")
            props = w.get("props", {})
            events = w.get("events", {})

            args: list[str] = []
            post_init_lines: list[str] = []
            typedef = WIDGET_REGISTRY.get(wtype)
            if typedef:
                for pdef in typedef.properties:
                    if pdef.name == "group":
                        g = props.get("group", "")
                        if g:
                            args.append(f"group={g}")
                        continue
                    # ImageWidget filepath is handled via load() not constructor
                    if pdef.name == "filepath" and wtype == "ImageWidget":
                        fpath = props.get("filepath", "")
                        if fpath:
                            post_init_lines.append(
                                f"        self.{wid}.load({_repr_value(fpath)})")
                        continue
                    if pdef.name in props:
                        val = props[pdef.name]
                        if val != pdef.default:
                            args.append(f"{pdef.name}={_repr_value(val)}")
                        elif pdef.category == "layout":
                            args.append(f"{pdef.name}={_repr_value(val)}")

            # Event handler kwargs
            for event_name, handler_name in events.items():
                if handler_name:
                    args.append(f"{event_name}=self.{handler_name}")

            args_str = ", ".join(args)
            lines.append(f"        self.{wid} = {wtype}({args_str})")
            for pil in post_init_lines:
                lines.append(pil)
            lines.append(f"        content.add_child(self.{wid})")
            lines.append("")

        lines.append(f"        self.{win_id}.set_content(content)")
        lines.append(f"        self.add_window(self.{win_id})")
        lines.append("")

    # Emit menu bar
    if has_menus:
        lines.append("        menu_bar = MenuBar(menus=[")
        for menu in data["menus"]:
            menu_title = menu.get("title", "")
            lines.append(f'            Menu("{menu_title}", [')
            for item in menu.get("items", []):
                if item.get("is_separator"):
                    lines.append("                MenuItem.separator(),")
                else:
                    label = item.get("label", "")
                    parts = [repr(label)]
                    shortcut = item.get("shortcut", "")
                    if shortcut:
                        parts.append(f"shortcut={repr(shortcut)}")
                    handler = item.get("handler", "")
                    if handler:
                        parts.append(f"action=self.{handler}")
                    enabled = item.get("enabled", True)
                    if not enabled:
                        parts.append("enabled=False")
                    lines.append(f"                MenuItem({', '.join(parts)}),")
            lines.append("            ]),")
        lines.append("        ])")
        lines.append("        self.set_menu(menu_bar)")
        lines.append("")

    # Event handler stubs
    for handler_name in sorted(all_handlers):
        lines.append(f"    def {handler_name}(self) -> None:")
        lines.append(f'        """TODO: Implement {handler_name}."""')
        lines.append("        pass")
        lines.append("")

    lines.append("")
    lines.append('if __name__ == "__main__":')
    lines.append(f"    app = {class_name}()")
    lines.append("    app.run()")
    lines.append("")

    return "\n".join(lines)


def save_python(code: str, path: str) -> None:
    """Write generated Python code to a file."""
    with open(path, "w") as f:
        f.write(code)
