#!/usr/bin/env python3
"""Generated by runtui RAD Designer — My Application."""

import sys
import os

# Add parent dir to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from runtui import (
    App, Button, TextInput, Window,
)
from runtui.widgets.container import Container
from runtui.layout.absolute import AbsoluteLayout


class MyApplicationApp(App):
    """Application: My Application."""

    def __init__(self) -> None:
        super().__init__(theme="light")
        # Calculator state variables
        self.stored_value = 0.0
        self.current_operation = None
        self.reset_next = False

    def on_ready(self) -> None:
        self.main_window = Window(
            title="Calculator",
            x=5, y=2, width=33, height=15,
        )

        content = Container()
        content._layout_manager = AbsoluteLayout()

        # Moved inp1 up from y=2 to y=1
        self.inp1 = TextInput(x=2, y=1, width=27, height=1, text="0")
        content.add_child(self.inp1)

        # Row 1: Moved up from y=4 to y=3
        self.btn_ac = Button(x=2, y=3, width=6, height=1, text='AC', on_click=self.btn_ac_click)
        content.add_child(self.btn_ac)

        self.btn_plus_minus = Button(x=9, y=3, width=6, height=1, text='+-', on_click=self.btn_plus_minus_click)
        content.add_child(self.btn_plus_minus)

        self.btn_percentage = Button(x=16, y=3, width=6, height=1, text=' %', on_click=self.btn_percentage_click)
        content.add_child(self.btn_percentage)

        self.btn_divide = Button(x=23, y=3, width=6, height=1, text=' ÷', on_click=self.btn_divide_click)
        content.add_child(self.btn_divide)

        # Row 2: Moved up from y=6 to y=5
        self.btn_7 = Button(x=2, y=5, width=6, height=1, text=' 7', on_click=self.btn_7_click)
        content.add_child(self.btn_7)

        self.btn_8 = Button(x=9, y=5, width=6, height=1, text=' 8', on_click=self.btn_8_click)
        content.add_child(self.btn_8)

        self.btn_9 = Button(x=16, y=5, width=6, height=1, text=' 9', on_click=self.btn_9_click)
        content.add_child(self.btn_9)

        self.btn_multiple = Button(x=23, y=5, width=6, height=1, text=' ×', on_click=self.btn_multiple_click)
        content.add_child(self.btn_multiple)

        # Row 3: Moved up from y=8 to y=7
        self.btn_4 = Button(x=2, y=7, width=6, height=1, text=' 4', on_click=self.btn_4_click)
        content.add_child(self.btn_4)

        self.btn_5 = Button(x=9, y=7, width=6, height=1, text=' 5', on_click=self.btn_5_click)
        content.add_child(self.btn_5)

        self.btn_6 = Button(x=16, y=7, width=6, height=1, text=' 6', on_click=self.btn_6_click)
        content.add_child(self.btn_6)

        self.btn_minus = Button(x=23, y=7, width=6, height=1, text=' -', on_click=self.btn_minus_click)
        content.add_child(self.btn_minus)

        # Row 4: Moved up from y=10 to y=9
        self.btn_1 = Button(x=2, y=9, width=6, height=1, text=' 1', on_click=self.btn_1_click)
        content.add_child(self.btn_1)

        self.btn_2 = Button(x=9, y=9, width=6, height=1, text=' 2', on_click=self.btn_2_click)
        content.add_child(self.btn_2)

        self.btn_3 = Button(x=16, y=9, width=6, height=1, text=' 3', on_click=self.btn_3_click)
        content.add_child(self.btn_3)

        self.btn_add = Button(x=23, y=9, width=6, height=1, text=' +', on_click=self.btn_add_click)
        content.add_child(self.btn_add)

        # Row 5: Moved up from y=12 to y=11
        self.btn_0 = Button(x=2, y=11, width=13, height=1, text=' 0       ', on_click=self.btn_0_click)
        content.add_child(self.btn_0)

        self.btn_dot = Button(x=16, y=11, width=6, height=1, text=' .', on_click=self.btn_dot_click)
        content.add_child(self.btn_dot)

        self.btn_equal = Button(x=23, y=11, width=6, height=1, text=' =', on_click=self.btn_equal_click)
        content.add_child(self.btn_equal)

        self.main_window.set_content(content)
        self.add_window(self.main_window)

    # --- Helper Methods ---

    def _add_digit(self, digit: str) -> None:
        """Helper to handle digit input."""
        current_text = self.inp1.text
        
        if self.reset_next:
            self.inp1.text = digit
            self.reset_next = False
        else:
            if current_text == "0":
                self.inp1.text = digit
            else:
                self.inp1.text = current_text + digit

    def _set_operation(self, op: str) -> None:
        """Helper to handle operator input."""
        # Calculate pending operations to allow chaining (e.g., 1+1+1)
        if self.current_operation is not None and not self.reset_next:
            self._calculate_result()
        
        try:
            self.stored_value = float(self.inp1.text)
        except ValueError:
            self.stored_value = 0.0
            
        self.current_operation = op
        self.reset_next = True

    def _calculate_result(self) -> None:
        """Helper to perform the calculation."""
        if not self.current_operation:
            return

        try:
            current_val = float(self.inp1.text)
            result = 0.0
            
            if self.current_operation == '+':
                result = self.stored_value + current_val
            elif self.current_operation == '-':
                result = self.stored_value - current_val
            elif self.current_operation == '*':
                result = self.stored_value * current_val
            elif self.current_operation == '/':
                if current_val == 0:
                    self.inp1.text = "Error"
                    self.reset_next = True
                    self.current_operation = None
                    return
                result = self.stored_value / current_val

            # Remove trailing .0 for clean integer display
            if result.is_integer():
                self.inp1.text = str(int(result))
            else:
                self.inp1.text = str(result)
                
        except Exception:
            self.inp1.text = "Error"
        
        # Keep stored value as result for further operations
        try:
            self.stored_value = float(self.inp1.text)
        except:
            self.stored_value = 0.0

    # --- Event Implementations ---

    def btn_0_click(self) -> None:
        self._add_digit('0')

    def btn_1_click(self) -> None:
        self._add_digit('1')

    def btn_2_click(self) -> None:
        self._add_digit('2')

    def btn_3_click(self) -> None:
        self._add_digit('3')

    def btn_4_click(self) -> None:
        self._add_digit('4')

    def btn_5_click(self) -> None:
        self._add_digit('5')

    def btn_6_click(self) -> None:
        self._add_digit('6')

    def btn_7_click(self) -> None:
        self._add_digit('7')

    def btn_8_click(self) -> None:
        self._add_digit('8')

    def btn_9_click(self) -> None:
        self._add_digit('9')

    def btn_ac_click(self) -> None:
        self.inp1.text = "0"
        self.stored_value = 0.0
        self.current_operation = None
        self.reset_next = False

    def btn_add_click(self) -> None:
        self._set_operation('+')

    def btn_divide_click(self) -> None:
        self._set_operation('/')

    def btn_dot_click(self) -> None:
        if self.reset_next:
            self.inp1.text = "0."
            self.reset_next = False
        elif "." not in self.inp1.text:
            self.inp1.text += "."

    def btn_equal_click(self) -> None:
        self._calculate_result()
        self.current_operation = None
        self.reset_next = True

    def btn_minus_click(self) -> None:
        self._set_operation('-')

    def btn_multiple_click(self) -> None:
        self._set_operation('*')

    def btn_percentage_click(self) -> None:
        try:
            val = float(self.inp1.text)
            self.inp1.text = str(val / 100)
            self.reset_next = True
        except ValueError:
            self.inp1.text = "Error"

    def btn_plus_minus_click(self) -> None:
        try:
            val = float(self.inp1.text)
            # Toggle negative/positive
            result = val * -1
            if result.is_integer():
                self.inp1.text = str(int(result))
            else:
                self.inp1.text = str(result)
        except ValueError:
            pass


if __name__ == "__main__":
    app = MyApplicationApp()
    app.run()