#!/usr/bin/env python3
"""Generated by runtui RAD Designer — My Application."""

import sys
import os
import math
import datetime

# Add parent dir to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

try:
    from PIL import Image, ImageDraw
except ImportError:
    print("This clock requires Pillow. Please run: pip install Pillow")
    sys.exit(1)

from runtui import (
    App, Label, StaticImage, Window,
)
from runtui.widgets.container import Container
from runtui.layout.absolute import AbsoluteLayout


class ClockWidget(StaticImage):
    """StaticImage that can be updated with a PIL image in memory."""

    def set_pil_image(self, img: Image.Image) -> None:
        self._image = img.convert("RGB")
        self._img_width = img.width
        self._img_height = img.height
        self._scaled_cache = None
        self._cache_key = ()
        self.invalidate()


def draw_clock_face(width: int = 400, height: int = 400) -> Image.Image:
    """Generate a PIL image of an analog clock."""
    img = Image.new("RGB", (width, height), (255, 255, 255))
    draw = ImageDraw.Draw(img)

    center_x = width // 2
    center_y = height // 2
    radius = min(center_x, center_y) - 10

    # Draw outer circle
    draw.ellipse(
        (center_x - radius, center_y - radius, center_x + radius, center_y + radius),
        outline=(255, 255, 255), width=4
    )

    # Draw ticks and numbers
    for i in range(12):
        angle_deg = i * 30 - 90
        angle_rad = math.radians(angle_deg)

        # Ticks
        tick_len = 15
        x_start = center_x + math.cos(angle_rad) * (radius - tick_len)
        y_start = center_y + math.sin(angle_rad) * (radius - tick_len)
        x_end = center_x + math.cos(angle_rad) * radius
        y_end = center_y + math.sin(angle_rad) * radius

        draw.line((x_start, y_start, x_end, y_end), fill=(200, 200, 200), width=3)

        # Numbers
        num_dist = radius - 35
        num_x = center_x + math.cos(angle_rad) * num_dist
        num_y = center_y + math.sin(angle_rad) * num_dist

        number_str = str(12 if i == 0 else i)
        draw.text((num_x - 5, num_y - 8), number_str, fill=(255, 255, 0))

    # Get current time
    now = datetime.datetime.now()

    # Hour hand
    hour_angle = (now.hour % 12 + now.minute / 60) * 30 - 90
    h_rad = math.radians(hour_angle)
    h_len = radius * 0.5
    draw.line(
        (center_x, center_y, center_x + math.cos(h_rad) * h_len, center_y + math.sin(h_rad) * h_len),
        fill=(0, 255, 255), width=8
    )

    # Minute hand
    min_angle = (now.minute + now.second / 60) * 6 - 90
    m_rad = math.radians(min_angle)
    m_len = radius * 0.7
    draw.line(
        (center_x, center_y, center_x + math.cos(m_rad) * m_len, center_y + math.sin(m_rad) * m_len),
        fill=(0, 255, 0), width=5
    )

    # Second hand
    sec_angle = now.second * 6 - 90
    s_rad = math.radians(sec_angle)
    s_len = radius * 0.85
    draw.line(
        (center_x, center_y, center_x + math.cos(s_rad) * s_len, center_y + math.sin(s_rad) * s_len),
        fill=(255, 0, 0), width=2
    )

    # Center dot
    draw.ellipse((center_x - 6, center_y - 6, center_x + 6, center_y + 6), fill=(255, 255, 255))

    return img


class MyApplicationApp(App):
    """Application: My Application."""

    def __init__(self) -> None:
        super().__init__(theme="light")

    def on_ready(self) -> None:
        self.main_window = Window(
            title="Clock",
            x=5, y=2, width=34, height=18,
        )

        content = Container()
        content._layout_manager = AbsoluteLayout()

        # Clock display using StaticImage
        self.clock_display = ClockWidget(x=1, y=1, width=30, height=15)
        content.add_child(self.clock_display)

        # Hour labels around the clock
        self.lbl_0 = Label(x=15, y=1, width=2, height=1, text='12')
        content.add_child(self.lbl_0)

        self.lbl_6 = Label(x=15, y=15, width=2, height=1, text=' 6')
        content.add_child(self.lbl_6)

        self.lbl_5 = Label(x=22, y=14, width=2, height=1, text=' 5')
        content.add_child(self.lbl_5)

        self.lbl_4 = Label(x=27, y=12, width=2, height=1, text=' 4')
        content.add_child(self.lbl_4)

        self.lbl_3 = Label(x=29, y=8, width=2, height=1, text=' 3')
        content.add_child(self.lbl_3)

        self.lbl_7 = Label(x=8, y=14, width=2, height=1, text=' 7')
        content.add_child(self.lbl_7)

        self.lbl_2 = Label(x=27, y=5, width=2, height=1, text=' 2')
        content.add_child(self.lbl_2)

        self.lbl_1 = Label(x=22, y=2, width=2, height=1, text=' 1')
        content.add_child(self.lbl_1)

        self.lbl_8 = Label(x=2, y=12, width=2, height=1, text=' 8')
        content.add_child(self.lbl_8)

        self.lbl_9 = Label(x=0, y=8, width=2, height=1, text=' 9')
        content.add_child(self.lbl_9)

        self.lbl_10 = Label(x=2, y=5, width=2, height=1, text='10')
        content.add_child(self.lbl_10)

        self.lbl_11 = Label(x=8, y=2, width=2, height=1, text='11')
        content.add_child(self.lbl_11)

        self.main_window.set_content(content)
        self.add_window(self.main_window)

        # Initial draw
        self.update_clock()

        # Update every second using Timer
        self.set_interval(0.25, self.update_clock)


    def update_clock(self) -> None:
        """Update the clock display."""
        img = draw_clock_face(400, 400)
        self.clock_display.set_pil_image(img)
        self.invalidate_all()


if __name__ == "__main__":
    app = MyApplicationApp()
    app.run()
